[theme]
base="dark"
primaryColor="#00C853"
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#FFFFFF"
font="sans serif"
linkColor="#00C853"
borderColor="#3A3F4B"
dataframeHeaderBackgroundColor="#262730"
codeBackgroundColor="#1B1E26"
showWidgetBorder=true

[theme.sidebar]
backgroundColor="#171922"
secondaryBackgroundColor="#262730"
textColor="#FFFFFF"
primaryColor="#00C853"
borderColor="#3A3F4B"
showWidgetBorder=true